var $jscomp={scope:{},findInternal:function(a,k,d){a instanceof String&&(a=String(a));for(var g=a.length,f=0;f<g;f++){var h=a[f];if(k.call(d,h,f,a))return{i:f,v:h}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,k,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[k]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,k,d,g){if(k){d=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var f=a[g];f in d||(d[f]={});d=d[f]}a=a[a.length-1];g=d[a];k=k(g);k!=g&&null!=k&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:k})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6-impl","es3");
(function(a){"function"===typeof define&&define.amd?define(["jquery","./grid.base"],a):"object"===typeof exports?a(require("jquery")):a(jQuery)})(function(a){var k=a.jgrid,d=k.jqID,g=a.fn.jqGrid,f=function(){var c=a.makeArray(arguments);c[0]="subGrid"+c[0].charAt(0).toUpperCase()+c[0].substring(1);c.unshift("");c.unshift("");c.unshift(this.p);return k.feedback.apply(this,c)},h=function(c,k){return this.each(function(){if(this.grid&&null!=c&&!0===this.p.subGrid){var e=a(this).jqGrid("getInd",c,!0);
a(e).find(">td."+k).trigger("click")}})};k.extend({setSubGrid:function(){return this.each(function(){var c=this.p,d=c.subGridModel[0];c.subGridOptions=a.extend({expandOnLoad:!1,delayOnLoad:50,selectOnExpand:!1,selectOnCollapse:!1,reloadOnExpand:!0},c.subGridOptions||{});c.colNames.unshift("");c.colModel.unshift({name:"subgrid",width:k.cell_width?c.subGridWidth+c.cellLayout:c.subGridWidth,labelClasses:"jqgh_subgrid",sortable:!1,resizable:!1,hidedlg:!0,search:!1,fixed:!0,frozen:!0});if(d)for(d.align=
a.extend([],d.align||[]),c=0;c<d.name.length;c++)d.align[c]=d.align[c]||"left"})},addSubGridCell:function(c,d,e,b){var l=this[0],f=l.p.subGridOptions;e=a.isFunction(f.hasSubgrid)?f.hasSubgrid.call(l,{rowid:e,iRow:d,iCol:c,data:b}):!0;return null==l||null==l.p||null==f?"":"<td role='gridcell' class='"+g.getGuiStyles.call(this,"subgrid.tdStart",e?"ui-sgcollapsed sgcollapsed":"")+"' "+l.formatCol(c,d)+">"+(e?"<div class='"+g.getGuiStyles.call(this,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+
g.getGuiStyles.call(this,"subgrid.button","sgbutton")+"'><span class='"+k.mergeCssClasses(f.commonIconClass,f.plusicon)+"'></span></a></div>":"&nbsp;")+"</td>"},addSubGrid:function(c,h){return this.each(function(){var e=this,b=e.p,l=b.subGridModel[0],p=function(a,b){return g.getGuiStyles.call(e,"subgrid."+a,b||"")},z=p("thSubgrid","ui-th-subgrid ui-th-column ui-th-"+b.direction),y=p("rowSubTable","ui-subtblcell"),A=p("row","ui-subgrid ui-row-"+b.direction),B=p("tdWithIcon","subgrid-cell"),C=p("tdData",
"subgrid-data"),q=function(b,c,e){e=l.align[e];c=a("<td"+(e?" style='text-align:"+e+";'":"")+"></td>").html(c);b.append(c)},v=function(c,e){var d=b.xmlReader.subgrid;a(d.root+" "+d.row,c).each(function(){var b,c,k=a("<tr class='"+y+"'></tr>");if(!0===d.repeatitems)a(d.cell,this).each(function(b){q(k,a(this).text()||"&#160;",b)});else if(b=l.mapping||l.name)for(c=0;c<b.length;c++)q(k,a(b[c],this).text()||"&#160;",c);e.append(k)})},w=function(c,e){var d,r,m,g,f,h=b.jsonReader.subgrid,n=k.getAccessor(c,
h.root);if(null!=n)for(r=0;r<n.length;r++){f=n[r];d=a("<tr class='"+y+"'></tr>");if(!0===h.repeatitems)for(h.cell&&(f=f[h.cell]),m=0;m<f.length;m++)q(d,f[m]||"&#160;",m);else if(g=l.mapping||l.name,g.length)for(m=0;m<g.length;m++)q(d,f[g[m]]||"&#160;",m);e.append(d)}},t=function(c,k,f){var g,m;g=p("legacyTable","ui-jqgrid-legacy-subgrid"+(!0===b.altRows&&a(e).jqGrid("isBootstrapGuiStyle")?" table-striped":""));var h=a("<table"+(g?" style='width:1px' role='presentation' class='"+g+"'":"")+"><thead></thead><tbody></tbody></table>"),
n=a("<tr></tr>");for(m=0;m<l.name.length;m++)g=a("<th class='"+z+"'></th>").html(l.name[m]).width(l.width[m]),n.append(g);n.appendTo(h[0].tHead);f(c,a(h[0].tBodies[0]));a("#"+d(b.id+"_"+k)).append(h);e.grid.hDiv.loading=!1;a("#load_"+d(b.id)).hide();return!1},D=function(c){var g=a(c).attr("id"),f={nd_:(new Date).getTime()},h,m;f[b.prmNames.subgridid]=g;if(!l)return!1;if(l.params)for(m=0;m<l.params.length;m++)h=b.iColByName[l.params[m]],void 0!==h&&(f[b.colModel[h].name]=a(c.cells[h]).text().replace(/\&#160\;/ig,
""));if(!e.grid.hDiv.loading)switch(e.grid.hDiv.loading=!0,a("#load_"+d(b.id)).show(),b.subgridtype||(b.subgridtype=b.datatype),a.isFunction(b.subgridtype)?b.subgridtype.call(e,f):b.subgridtype=b.subgridtype.toLowerCase(),b.subgridtype){case "xml":case "json":a.ajax(a.extend({type:b.mtype,url:a.isFunction(b.subGridUrl)?b.subGridUrl.call(e,f):b.subGridUrl,dataType:b.subgridtype,context:g,data:k.serializeFeedback.call(e,b.serializeSubGridData,"jqGridSerializeSubGridData",f),success:function(c){a(e.grid.eDiv).hide();
t(c,this,"xml"===b.subgridtype?v:w)},error:function(c,f,g){var k=void 0===b.loadSubgridError?b.loadError:b.loadSubgridError;a.isFunction(k)&&k.call(e,c,f,g);b.subGridOptions.noEmptySubgridOnError?(e.grid.hDiv.loading=!1,a("#load_"+d(b.id)).hide()):t(null,this,"xml"===b.subgridtype?v:w)}},k.ajaxOptions,b.ajaxSubgridOptions||{}))}return!1},E=function(){var d=a(this).parent("tr")[0],h=d.nextSibling,l=d.id,n=b.id+"_"+l,m=function(a){return k.mergeCssClasses(b.subGridOptions.commonIconClass,b.subGridOptions[a])},
p=1;a.each(b.colModel,function(){!0!==this.hidden&&"rn"!==this.name&&"cb"!==this.name||p++});if(a(this).hasClass("sgcollapsed")){if(!0===b.subGridOptions.reloadOnExpand||!1===b.subGridOptions.reloadOnExpand&&!a(h).hasClass("ui-subgrid")){h=1<=c?"<td colspan='"+c+"'>&#160;</td>":"";if(!f.call(e,"beforeExpand",n,l))return;a(d).after("<tr role='row' class='"+A+"'>"+h+"<td class='"+B+"'><span class='"+m("openicon")+"'></span></td><td colspan='"+parseInt(b.colNames.length-p,10)+"' class='"+C+"'><div id='"+
n+"' class='tablediv'></div></td></tr>");a(e).triggerHandler("jqGridSubGridRowExpanded",[n,l]);a.isFunction(b.subGridRowExpanded)?b.subGridRowExpanded.call(e,n,l):D(d)}else a(h).show();a(this).html("<div class='"+g.getGuiStyles.call(e,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+g.getGuiStyles.call(e,"subgrid.button","sgbutton")+"'><span class='"+m("minusicon")+"'></span></a></div>").removeClass("sgcollapsed").addClass("sgexpanded");b.subGridOptions.selectOnExpand&&a(e).jqGrid("setSelection",
l)}else if(a(this).hasClass("sgexpanded")){if(!f.call(e,"beforeCollapse",n,l))return;!0===b.subGridOptions.reloadOnExpand?a(h).remove(".ui-subgrid"):a(h).hasClass("ui-subgrid")&&a(h).hide();a(this).html("<div class='"+g.getGuiStyles.call(e,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+g.getGuiStyles.call(e,"subgrid.button","sgbutton")+"'><span class='"+m("plusicon")+"'></span></a></div>").removeClass("sgexpanded").addClass("sgcollapsed");b.subGridOptions.selectOnCollapse&&a(e).jqGrid("setSelection",
l)}return!1},x,n,u=1;if(e.grid){x=e.rows.length;void 0!==h&&0<h&&(u=h,x=h+1);for(;u<x;)n=e.rows[u],a(n).hasClass("jqgrow")&&(n=a(n.cells[c]),n.hasClass("ui-sgcollapsed")&&(b.scroll&&n.unbind("click"),n.bind("click",E))),u++;!0===b.subGridOptions.expandOnLoad&&a(e.rows).filter(".jqgrow").each(function(c,b){a(b.cells[0]).click()});e.subGridXml=function(a,b){return t(a,b,v)};e.subGridJson=function(a,b){return t(a,b,w)}}})},expandSubGridRow:function(a){return h.call(this,a,"sgcollapsed")},collapseSubGridRow:function(a){return h.call(this,
a,"sgexpanded")},toggleSubGridRow:function(a){return h.call(this,a,"ui-sgcollapsed")}})});
//# sourceMappingURL=grid.subgrid.map
