(function(h){"function"===typeof define&&define.amd?define(["jquery","./grid.grouping"],h):"object"===typeof exports?h(require("jquery")):h(jQuery)})(function(h){function J(d,c,l){if(!(this instanceof J))return new J(d);this.aggregator=d;this.finilized=!1;this.context=c;this.pivotOptions=l}function E(d,c,l,n,m){var k=n.length,x=function(b,a){var d=b,c=a;null==d&&(d="");null==c&&(c="");d=String(d);c=String(c);this.caseSensitive||(d=d.toUpperCase(),c=c.toUpperCase());if(d===c){if(b===a)return 0;if(void 0===
b)return-1;if(void 0===a)return 1;if(null===b)return-1;if(null===a)return 1}return d<c?-1:1},g=function(b,a){b=Number(b);a=Number(a);return b===a?0:b<a?-1:1},e=function(b,a){b=Math.floor(Number(b));a=Math.floor(Number(a));return b===a?0:b<a?-1:1};this.items=[];this.indexesOfSourceData=[];this.trimByCollect=d;this.caseSensitive=c;this.skipSort=l;this.fieldLength=k;this.fieldNames=Array(k);this.fieldSortDirection=Array(k);this.fieldCompare=Array(k);for(d=0;d<k;d++){c=n[d];this.fieldNames[d]=c[m||"dataName"];
switch(c.sorttype){case "integer":case "int":this.fieldCompare[d]=e;break;case "number":case "currency":case "float":this.fieldCompare[d]=g;break;default:this.fieldCompare[d]=h.isFunction(c.compare)?c.compare:x}this.fieldSortDirection[d]="desc"===c.sortorder?-1:1}}var P=h.jgrid;J.prototype.calc=function(d,c,l,n,m){if(void 0!==d)switch(this.result=this.result||0,d=parseFloat(d),this.aggregator){case "sum":this.result+=d;break;case "count":this.result++;break;case "avg":this.finilized?(this.count=this.count||
0,this.result=(this.result*this.count+d)/(this.count+1)):(this.result+=d,this.count=this.count||0);this.count++;break;case "min":this.result=Math.min(this.result,d);break;case "max":this.result=Math.max(this.result,d);break;default:h.isFunction(this.aggregator)&&(this.result=this.aggregator.call(this.context,{previousResult:this.result,value:d,fieldName:c,item:l,iItem:n,items:m}))}};J.prototype.getResult=function(d,c,l){if(void 0!==this.result||l)l&&void 0!==this.result&&(this.count=this.result=0),
void 0===this.result||this.finilized||"avg"!==this.aggregator||(this.result/=this.count,this.finilized=!0),d[c]=this.result};E.prototype.compareVectorsEx=function(d,c){var l=this.fieldLength,h,m;for(h=0;h<l;h++)if(m=this.fieldCompare[h](d[h],c[h]),0!==m)return{index:h,result:m};return{index:-1,result:0}};E.prototype.getIndexOfDifferences=function(d,c){return null===c||null===d?0:this.compareVectorsEx(d,c).index};E.prototype.compareVectors=function(d,c){var h=this.compareVectorsEx(d,c);return 0<(0<=
h.index?this.fieldSortDirection[h.index]:1)?h.result:-h.result};E.prototype.getItem=function(d){return this.items[d]};E.prototype.getIndexLength=function(){return this.items.length};E.prototype.getIndexesOfSourceData=function(d){return this.indexesOfSourceData[d]};E.prototype.createDataIndex=function(d){var c,l=d.length,n=this.fieldLength,m,k,x=this.fieldNames,g=this.indexesOfSourceData,e,b,a=this.items,r;for(c=0;c<l;c++){b=d[c];m=Array(n);for(e=0;e<n;e++)k=b[x[e]],void 0!==k&&("string"===typeof k&&
this.trimByCollect&&(k=h.trim(k)),m[e]=k);b=0;r=a.length-1;if(0>r)a.push(m),g.push([c]);else if(k=this.compareVectors(m,a[r]),0===k)g[r].push(c);else if(1===k||this.skipSort)a.push(m),g.push([c]);else if(k=this.compareVectors(a[0],m),1===k)a.unshift(m),g.unshift([c]);else if(0===k)g[0].push(c);else for(;;){if(2>r-b){a.splice(r,0,m);g.splice(r,0,[c]);break}e=Math.floor((b+r)/2);k=this.compareVectors(a[e],m);if(0===k){g[e].push(c);break}1===k?r=e:b=e}}};P.extend({pivotSetup:function(d,c){var l=this[0],
n=h.isArray,m={},k={groupField:[],groupSummary:[],groupSummaryPos:[]},x={grouping:!0,groupingView:k},g=h.extend({totals:!1,useColSpanStyle:!1,trimByCollect:!0,skipSortByX:!1,skipSortByY:!1,caseSensitive:!1,footerTotals:!1,groupSummary:!0,groupSummaryPos:"header",frozenStaticCols:!1,defaultFormatting:!0,data:d},c||{}),e,b,a,r=d.length,F,f,w,y,C,U,Q=g.xDimension,z=g.yDimension,G=g.aggregates,N,r=g.totalText||g.totals||g.rowTotals||g.totalHeader,t,K=n(Q)?Q.length:0;y=n(z)?z.length:0;var p=n(G)?G.length:
0,A=y-(1===p?1:0),H=[],L=[],R=[],n=[],Y=["pivotInfos"],V=Array(p),O=Array(y),S,Z,v,W,M,I,B,q,D,T,u;b=function(a,b,c){a=new E(g.trimByCollect,g.caseSensitive,b,a);h.isFunction(c)&&(a.compareVectorsEx=c);a.createDataIndex(d);return a};var ba=function(a,b,d,c,e){var f,k;switch(a){case 1:f=z[c].totalText||"{0} {1} {2}";k="y"+e+"t"+c;break;case 2:f=g.totalText||"{0}";k="t";break;default:f=1<p?b.label||"{0}":h.isFunction(z[c].label)?z[c].label:u.getItem(e)[c],k="y"+e}a=h.extend({},b,{name:k+(1<p?"a"+d:
""),label:h.isFunction(f)?f.call(l,2===a?{aggregate:b,iAggregate:d,pivotOptions:g}:1===a?{yIndex:u.getItem(e),aggregate:b,iAggregate:d,yLevel:c,pivotOptions:g}:{yData:u.getItem(e)[c],yIndex:u.getItem(e),yLevel:c,pivotOptions:g}):P.template.apply(l,2===a?[String(f),b.aggregator,b.member,d]:[String(f),b.aggregator,b.member,u.getItem(e)[c],c])});delete a.member;delete a.aggregator;return a};C=function(a,b,c){var d,e;for(d=0;d<p;d++)e=G[d],void 0===e.template&&void 0===e.formatter&&g.defaultFormatting&&
(e.template="count"===e.aggregator?"integer":"number"),R.push(ba(a,e,d,b,c))};S=function(a,b,d){var c,e,f,g;for(c=A-1;c>=b;c--)if(L[c]){for(e=0;e<=c;e++)D=H[e].groupHeaders,D[D.length-1].numberOfColumns+=p;F=z[c];f=F.totalHeader;g=F.headerOnTop;for(e=c+1;e<=A-1;e++)H[e].groupHeaders.push({titleText:g&&e===c+1||!g&&e===A-1?h.isFunction(f)?f.call(l,d,c):P.template.call(l,String(f||""),d[c],c):"",startColumnName:"y"+(a-1)+"t"+c+(1===p?"":"a0"),numberOfColumns:p})}};var X=function(a){a=new J("count"===
G[a].aggregator?"sum":G[a].aggregator,l,c);a.groupInfo={iRows:[],rows:[],ys:[],iYs:[]};return a},ca=function(){var a,b;for(a=A-1;0<=a;a--)if(L[a])for(null==O[a]&&(O[a]=Array(p)),b=0;b<p;b++)O[a][b]=X(b)},aa=function(a,b,c,d){var e,f=u.getIndexOfDifferences(b,c),g,h;if(null!==c)for(f=Math.max(f,0),e=A-1;e>=f;e--)g="y"+a+"t"+e+(1<p?"a"+d:""),L[e]&&void 0===B[g]&&(h=O[e][d],h.getResult(B,g),B.pivotInfos[g]={colType:1,iA:d,a:G[d],level:e,iRows:h.groupInfo.iRows,rows:h.groupInfo.rows,ys:h.groupInfo.ys,
iYs:h.groupInfo.iYs},b!==c&&(O[e][d]=X(d)))},da=function(a,b,c,e,f,g,k){var l;if(a!==b)for(b=A-1;0<=b;b--)L[b]&&(l=O[b][e],l.calc(f[c.member],c.member,f,g,d),l=l.groupInfo,0>h.inArray(k,l.iYs)&&(l.iYs.push(k),l.ys.push(a)),0>h.inArray(g,l.iRows)&&(l.iRows.push(g),l.rows.push(f)))};if(0===K||0===p)throw"xDimension or aggregates options are not set!";T=b(Q,g.skipSortByX,g.compareVectorsByX);u=b(z,g.skipSortByY,g.compareVectorsByY);c.xIndex=T;c.yIndex=u;for(b=0;b<K;b++)a=Q[b],f={name:"x"+b,label:null!=
a.label?h.isFunction(a.label)?a.label.call(l,a,b,g):a.label:a.dataName,frozen:g.frozenStaticCols},b<K-1&&!a.skipGrouping&&!a.additionalProperty&&(k.groupField.push(f.name),k.groupSummary.push(g.groupSummary),k.groupSummaryPos.push(g.groupSummaryPos)),f=h.extend(f,a),delete f.dataName,delete f.footerText,a.additionalProperty?Y.push(f.name):(R.push(f),x.sortname=f.name);2>K&&(x.grouping=!1);k.hideFirstGroupCol=!0;for(b=0;b<y;b++)F=z[b],L.push(F.totals||F.rowTotals||F.totalText||F.totalHeader?!0:!1);
q=u.getItem(0);C(0,y-1,0);k=u.getIndexLength();for(f=1;f<k;f++){v=u.getItem(f);b=u.getIndexOfDifferences(v,q);for(a=A-1;a>=b;a--)L[a]&&C(1,a,f-1);q=v;C(0,y-1,f)}for(b=A-1;0<=b;b--)L[b]&&C(1,b,k-1);r&&C(2);q=u.getItem(0);for(a=0;a<A;a++)H.push({useColSpanStyle:g.useColSpanStyle,groupHeaders:[{titleText:h.isFunction(z[a].label)?z[a].label.call(l,{yData:q[a],yIndex:q,yLevel:a,pivotOptions:g}):q[a],startColumnName:1===p?"y0":"y0a0",numberOfColumns:p}]});for(f=1;f<k;f++){v=u.getItem(f);b=u.getIndexOfDifferences(v,
q);S(f,b,q);for(a=A-1;a>=b;a--)H[a].groupHeaders.push({titleText:h.isFunction(z[a].label)?z[a].label.call(l,{yData:v[a],yIndex:v,yLevel:a,pivotOptions:g}):v[a],startColumnName:"y"+f+(1===p?"":"a0"),numberOfColumns:p});for(a=0;a<b;a++)D=H[a].groupHeaders,D[D.length-1].numberOfColumns+=p;q=v}S(k,0,q);if(r)for(b=0;b<A;b++)H[b].groupHeaders.push({titleText:b<A-1?"":g.totalHeader||"",startColumnName:"t"+(1===p?"":"a0"),numberOfColumns:p});S=T.getIndexLength();for(y=0;y<S;y++){a=T.getItem(y);C={iX:y,x:a};
B={pivotInfos:C};for(b=0;b<K;b++)B["x"+b]=a[b];Z=T.getIndexesOfSourceData(y);if(r)for(a=0;a<p;a++)V[a]=X(a);q=null;ca();for(f=0;f<k;f++){v=u.getItem(f);W=u.getIndexesOfSourceData(f);for(a=0;a<p;a++){null!==q&&aa(f-1,v,q,a);M=[];for(b=0;b<W.length;b++)w=W[b],0<=h.inArray(w,Z)&&M.push(w);if(0<M.length){U=Array(M.length);I=G[a];N=new J(I.aggregator,l,c);for(w=0;w<M.length;w++)b=M[w],e=d[b],U[w]=e,N.calc(e[I.member],I.member,e,b,d),r&&(t=V[a],t.calc(e[I.member],I.member,e,b,d),t=t.groupInfo,0>h.inArray(b,
t.iYs)&&(t.iYs.push(f),t.ys.push(v)),0>h.inArray(b,t.iRows)&&(t.iRows.push(b),t.rows.push(e))),da(v,q,I,a,e,b,f);e="y"+f+(1===p?"":"a"+a);N.getResult(B,e);C[e]={colType:0,iY:f,y:v,iA:a,a:I,iRows:M,rows:U}}}q=v}if(null!==q)for(a=0;a<p;a++)aa(k-1,q,q,a);if(r)for(a=0;a<p;a++)e="t"+(1===p?"":"a"+a),t=V[a],t.getResult(B,e),t=t.groupInfo,C[e]={colType:2,iA:a,a:G[a],iRows:t.iRows,rows:t.rows,iYs:t.iYs,ys:t.ys};n.push(B)}if(g.footerTotals||g.colTotals){r=n.length;for(b=0;b<K;b++)m["x"+b]=Q[b].footerText||
"";for(b=K;b<R.length;b++){e=R[b].name;N=new J(g.footerAggregator||"sum",l,c);for(w=0;w<r;w++)B=n[w],N.calc(B[e],e,B,w,n);N.getResult(m,e)}}c.colHeaders=H;return{colModel:R,additionalProperties:Y,options:c,rows:n,groupOptions:x,groupHeaders:H,summary:m}},jqPivot:function(d,c,l,n){return this.each(function(){function m(){var e=g.pivotSetup.call(x,d,c),b=e.groupHeaders,a=e.summary,m=0,n;for(n in a)a.hasOwnProperty(n)&&m++;a=0<m?!0:!1;m=e.groupOptions.groupingView;n=P.from.call(k,e.rows);var f;if(c.skipSortByX)for(f=
0;f<m.groupField.length;f++)n.orderBy(m.groupField[f],null!=l&&l.groupingView&&null!=l.groupingView.groupOrder&&"desc"===l.groupingView.groupOrder[f]?"d":"a","text","");c.data=d;g.call(x,h.extend(!0,{datastr:h.extend(n.select(),a?{userdata:e.summary}:{}),datatype:"jsonstring",footerrow:a,userDataOnFooter:a,colModel:e.colModel,additionalProperties:e.additionalProperties,pivotOptions:e.options,viewrecords:!0,sortname:c.xDimension[0].dataName},e.groupOptions,l||{}));if(b.length)for(f=0;f<b.length;f++)b[f]&&
b[f].groupHeaders.length&&g.setGroupHeaders.call(x,b[f]);c.frozenStaticCols&&g.setFrozenColumns.call(x)}var k=this,x=h(k),g=h.fn.jqGrid;"string"===typeof d?h.ajax(h.extend({url:d,dataType:"json",success:function(c){d=P.getAccessor(c,n&&n.reader?n.reader:"rows");m()}},n||{})):m()})}})});
//# sourceMappingURL=grid.pivot.map
