(function(a){"function"===typeof define&&define.amd?define(["jquery","./grid.base","./grid.common"],a):"object"===typeof exports?a(require("jquery")):a(jQuery)})(function(a){var m=a.jgrid;a.fn.jqFilter=function(k){if("string"===typeof k){var r=a.fn.jqFilter[k];if(!r)throw"jqFilter - No such method: "+k;var C=a.makeArray(arguments).slice(1);return r.apply(this,C)}var b=a.extend(!0,{filter:null,columns:[],onChange:null,afterRedraw:null,checkValues:null,error:!1,errmsg:"",errorcheck:!0,showQuery:!0,
sopt:null,ops:[],operands:null,numopts:"eq ne lt le gt ge nu nn in ni".split(" "),stropts:"eq ne bw bn ew en cn nc nu nn in ni".split(" "),strarr:["text","string","blob"],groupOps:[{op:"AND",text:"AND"},{op:"OR",text:"OR"}],groupButton:!0,ruleButtons:!0,direction:"ltr"},m.filter,k||{});return this.each(function(){if(!this.filter){this.p=b;if(null===b.filter||void 0===b.filter)b.filter={groupOp:b.groupOps[0].op,rules:[],groups:[]};var k,r=b.columns.length,e,E=/msie/i.test(navigator.userAgent)&&!window.opera,
z=function(){return a("#"+m.jqID(b.id))[0]||null},q=function(f,b){return a(z()).jqGrid("getGuiStyles",f,b||"")},A=function(f){return a(z()).jqGrid("getGridRes","search."+f)},D=q("states.error"),C=q("dialog.content");b.initFilter=a.extend(!0,{},b.filter);if(r){for(k=0;k<r;k++)e=b.columns[k],e.stype?e.inputtype=e.stype:e.inputtype||(e.inputtype="text"),e.sorttype?e.searchtype=e.sorttype:e.searchtype||(e.searchtype="string"),void 0===e.hidden&&(e.hidden=!1),e.label||(e.label=e.name),e.index&&(e.name=
e.index),e.hasOwnProperty("searchoptions")||(e.searchoptions={}),e.hasOwnProperty("searchrules")||(e.searchrules={});b.showQuery&&a(this).append("<table class='queryresult "+C+"' style='display:block;max-width:440px;border:0px none;' dir='"+b.direction+"'><tbody><tr><td class='query'></td></tr></tbody></table>");var F=function(f,l){var c=[!0,""],g=z();if(a.isFunction(l.searchrules))c=l.searchrules.call(g,f,l);else if(m&&m.checkValues)try{c=m.checkValues.call(g,f,-1,l.searchrules,l.label)}catch(t){}c&&
c.length&&!1===c[0]&&(b.error=!c[0],b.errmsg=c[1])};this.onchange=function(){b.error=!1;b.errmsg="";return a.isFunction(b.onChange)?b.onChange.call(this,b):!1};this.reDraw=function(){a("table.group:first",this).remove();var f=this.createTableForGroup(b.filter,null);a(this).append(f);a.isFunction(b.afterRedraw)&&b.afterRedraw.call(this,b)};this.createTableForGroup=function(f,l){var c=this,g,t=a("<table class='"+q("searchDialog.operationGroup","group")+"' style='border:0px none;'><tbody></tbody></table>"),
d="left";"rtl"===b.direction&&(d="right",t.attr("dir","rtl"));null===l&&t.append("<tr class='error' style='display:none;'><th colspan='5' class='"+D+"' align='"+d+"'></th></tr>");var h=a("<tr></tr>");t.append(h);d=a("<th colspan='5' align='"+d+"'></th>");h.append(d);if(!0===b.ruleButtons){var k=a("<select class='"+q("searchDialog.operationSelect","opsel")+"'></select>");d.append(k);var h="",e;for(g=0;g<b.groupOps.length;g++)e=f.groupOp===c.p.groupOps[g].op?" selected='selected'":"",h+="<option value='"+
c.p.groupOps[g].op+"'"+e+">"+c.p.groupOps[g].text+"</option>";k.append(h).bind("change",function(){f.groupOp=a(k).val();c.onchange()})}h="<span></span>";b.groupButton&&(h=a("<input type='button' value='+ {}' title='"+A("addGroupTitle")+"' class='"+q("searchDialog.addGroupButton","add-group")+"'/>"),h.bind("click",function(){void 0===f.groups&&(f.groups=[]);f.groups.push({groupOp:b.groupOps[0].op,rules:[],groups:[]});c.reDraw();c.onchange();return!1}));d.append(h);if(!0===b.ruleButtons){var h=a("<input type='button' value='+' title='"+
A("addRuleTitle")+"' class='"+q("searchDialog.addRuleButton","add-rule ui-add")+"'/>"),m;h.bind("click",function(){var b,d,h;void 0===f.rules&&(f.rules=[]);for(g=0;g<c.p.columns.length;g++)if(b=void 0===c.p.columns[g].search?!0:c.p.columns[g].search,d=!0===c.p.columns[g].hidden,(h=!0===c.p.columns[g].searchoptions.searchhidden)&&b||b&&!d){m=c.p.columns[g];break}b=m.searchoptions.sopt?m.searchoptions.sopt:c.p.sopt?c.p.sopt:-1!==a.inArray(m.searchtype,c.p.strarr)?c.p.stropts:c.p.numopts;f.rules.push({field:m.name,
op:b[0],data:""});c.reDraw();return!1});d.append(h)}null!==l&&(h=a("<input type='button' value='-' title='"+A("deleteGroupTitle")+"' class='"+q("searchDialog.deleteGroupButton","delete-group")+"'/>"),d.append(h),h.bind("click",function(){for(g=0;g<l.groups.length;g++)if(l.groups[g]===f){l.groups.splice(g,1);break}c.reDraw();c.onchange();return!1}));if(void 0!==f.groups)for(g=0;g<f.groups.length;g++)d=a("<tr></tr>"),t.append(d),h=a("<td class='first'></td>"),d.append(h),h=a("<td colspan='4'></td>"),
h.append(this.createTableForGroup(f.groups[g],f)),d.append(h);void 0===f.groupOp&&(f.groupOp=c.p.groupOps[0].op);if(void 0!==f.rules)for(g=0;g<f.rules.length;g++)t.append(this.createTableRowForRule(f.rules[g],f));return t};this.createTableRowForRule=function(f,l){var c=this,g=z(),k=a("<tr></tr>"),d,h,e,n="",u;k.append("<td class='first'></td>");var p=a("<td class='columns'></td>");k.append(p);var r=a("<select class='"+q("searchDialog.label","selectLabel")+"'></select>"),w,v=[];p.append(r);r.bind("change",
function(){f.field=a(r).val();var b=a(this).parents("tr:first"),d,l;for(l=0;l<c.p.columns.length;l++)if(c.p.columns[l].name===f.field){d=c.p.columns[l];break}if(d){var e=a.extend({},d.searchoptions||{},{id:m.randId(),name:d.name,mode:"search"});E&&"text"===d.inputtype&&!e.size&&(e.size=10);var k=m.createEl.call(g,d.inputtype,e,"",!0,c.p.ajaxSelectOptions||{},!0);a(k).addClass(q("searchDialog.elem","input-elm"));h=e.sopt?e.sopt:c.p.sopt?c.p.sopt:-1!==a.inArray(d.searchtype,c.p.strarr)?c.p.stropts:
c.p.numopts;d="";var t=0,n,p;v=[];a.each(c.p.ops,function(){v.push(this.oper)});c.p.cops&&a.each(c.p.cops,function(c){v.push(c)});for(l=0;l<h.length;l++)p=h[l],w=a.inArray(h[l],v),-1!==w&&(n=c.p.ops[w],n=void 0!==n?n.text:c.p.cops[p].text,0===t&&(f.op=p),d+="<option value='"+p+"'>"+n+"</option>",t++);a(".selectopts",b).empty().append(d);a(".selectopts",b)[0].selectedIndex=0;m.msie&&9>m.msiever()&&(l=parseInt(a("select.selectopts",b)[0].offsetWidth,10)+1,a(".selectopts",b).width(l),a(".selectopts",
b).css("width","auto"));a(".data",b).empty().append(k);m.bindEv.call(g,k,e);a(".input-elm",b).bind("change",function(b){b=b.target;f.data="SPAN"===b.nodeName.toUpperCase()&&e&&a.isFunction(e.custom_value)?e.custom_value.call(g,a(b).children(".customelement:first"),"get"):b.value;c.onchange()});setTimeout(function(){f.data=a(k).val();c.onchange()},0)}});var p=0,x,y;for(d=0;d<c.p.columns.length;d++)if(u=void 0===c.p.columns[d].search?!0:c.p.columns[d].search,x=!0===c.p.columns[d].hidden,(y=!0===c.p.columns[d].searchoptions.searchhidden)&&
u||u&&!x)u="",f.field===c.p.columns[d].name&&(u=" selected='selected'",p=d),n+="<option value='"+c.p.columns[d].name+"'"+u+">"+c.p.columns[d].label+"</option>";r.append(n);n=a("<td class='operators'></td>");k.append(n);e=b.columns[p];E&&"text"===e.inputtype&&!e.searchoptions.size&&(e.searchoptions.size=10);p=m.createEl.call(g,e.inputtype,a.extend({},e.searchoptions||{},{id:m.randId(),name:e.name}),f.data,!0,c.p.ajaxSelectOptions||{},!0);if("nu"===f.op||"nn"===f.op)a(p).attr("readonly","true"),a(p).attr("disabled",
"true");var B=a("<select class='"+q("searchDialog.operator","selectopts")+"'></select>");n.append(B);B.bind("change",function(){f.op=a(B).val();var b=a(this).parents("tr:first"),b=a(".input-elm",b)[0];"nu"===f.op||"nn"===f.op?(f.data="","SELECT"!==b.tagName.toUpperCase()&&(b.value=""),b.setAttribute("readonly","true"),b.setAttribute("disabled","true")):("SELECT"===b.tagName.toUpperCase()&&(f.data=b.value),b.removeAttribute("readonly"),b.removeAttribute("disabled"));c.onchange()});h=e.searchoptions.sopt?
e.searchoptions.sopt:c.p.sopt?c.p.sopt:-1!==a.inArray(e.searchtype,c.p.strarr)?c.p.stropts:c.p.numopts;n="";a.each(c.p.ops,function(){v.push(this.oper)});c.p.cops&&a.each(c.p.cops,function(c){v.push(c)});for(d=0;d<h.length;d++)y=h[d],w=a.inArray(h[d],v),-1!==w&&(x=c.p.ops[w],u=f.op===y?" selected='selected'":"",n+="<option value='"+y+"'"+u+">"+(void 0!==x?x.text:c.p.cops[y].text)+"</option>");B.append(n);n=a("<td class='data'></td>");k.append(n);n.append(p);m.bindEv.call(g,p,e.searchoptions);a(p).addClass(q("searchDialog.elem",
"input-elm")).bind("change",function(){f.data="custom"===e.inputtype?e.searchoptions.custom_value.call(g,a(this).children(".customelement:first"),"get"):a(this).val();c.onchange()});n=a("<td></td>");k.append(n);!0===b.ruleButtons&&(p=a("<input type='button' value='-' title='"+A("deleteRuleTitle")+"' class='"+q("searchDialog.deleteRuleButton","delete-rule ui-del")+"'/>"),n.append(p),p.bind("click",function(){for(d=0;d<l.rules.length;d++)if(l.rules[d]===f){l.rules.splice(d,1);break}c.reDraw();c.onchange();
return!1}));return k};this.getStringForGroup=function(b){var a="(",c;if(void 0!==b.groups)for(c=0;c<b.groups.length;c++){1<a.length&&(a+=" "+b.groupOp+" ");try{a+=this.getStringForGroup(b.groups[c])}catch(g){alert(g)}}if(void 0!==b.rules)try{for(c=0;c<b.rules.length;c++)1<a.length&&(a+=" "+b.groupOp+" "),a+=this.getStringForRule(b.rules[c])}catch(g){alert(g)}a+=")";return"()"===a?"":a};this.getStringForRule=function(f){var e="",c="",g,k,d=f.data,h;for(g=0;g<b.ops.length;g++)if(b.ops[g].oper===f.op){e=
b.operands.hasOwnProperty(f.op)?b.operands[f.op]:"";c=b.ops[g].oper;break}if(""===c&&null!=b.cops)for(h in b.cops)if(b.cops.hasOwnProperty(h)&&(c=h,e=b.cops[h].operand,a.isFunction(b.cops[h].buildQueryValue)))return b.cops[h].buildQueryValue.call(b,{cmName:f.field,searchValue:d,operand:e});for(g=0;g<b.columns.length;g++)if(b.columns[g].name===f.field){k=b.columns[g];break}if(null==k)return"";if("bw"===c||"bn"===c)d+="%";if("ew"===c||"en"===c)d="%"+d;if("cn"===c||"nc"===c)d="%"+d+"%";if("in"===c||
"ni"===c)d=" ("+d+")";b.errorcheck&&F(f.data,k);return-1!==a.inArray(k.searchtype,["int","integer","float","number","currency"])||"nn"===c||"nu"===c?f.field+" "+e+" "+d:f.field+" "+e+' "'+d+'"'};this.resetFilter=function(){b.filter=a.extend(!0,{},b.initFilter);this.reDraw();this.onchange()};this.hideError=function(){a("th."+D,this).html("");a("tr.error",this).hide()};this.showError=function(){a("th."+D,this).html(b.errmsg);a("tr.error",this).show()};this.toUserFriendlyString=function(){return this.getStringForGroup(b.filter)};
this.toString=function(){function a(c){var b="(",k;if(void 0!==c.groups)for(k=0;k<c.groups.length;k++)1<b.length&&(b="OR"===c.groupOp?b+" || ":b+" && "),b+=a(c.groups[k]);if(void 0!==c.rules)for(k=0;k<c.rules.length;k++){1<b.length&&(b="OR"===c.groupOp?b+" || ":b+" && ");var d=c.rules[k];if(e.p.errorcheck){for(var h=void 0,m=void 0,h=0;h<e.p.columns.length;h++)if(e.p.columns[h].name===d.field){m=e.p.columns[h];break}m&&F(d.data,m)}b+=d.op+"(item."+d.field+",'"+d.data+"')"}b+=")";return"()"===b?"":
b}var e=this;return a(b.filter)};this.reDraw();if(b.showQuery)this.onchange();this.filter=!0}}})};a.extend(a.fn.jqFilter,{toSQLString:function(){var a="";this.each(function(){a=this.toUserFriendlyString()});return a},filterData:function(){var a;this.each(function(){a=this.p.filter});return a},getParameter:function(a){return void 0!==a&&this.p.hasOwnProperty(a)?this.p[a]:this.p},resetFilter:function(){return this.each(function(){this.resetFilter()})},addFilter:function(a){"string"===typeof a&&(a=m.parse(a));
this.each(function(){this.p.filter=a;this.reDraw();this.onchange()})}})});
//# sourceMappingURL=grid.filter.map
