var $jscomp={scope:{},findInternal:function(a,x,v){a instanceof String&&(a=String(a));for(var r=a.length,u=0;u<r;u++){var y=a[u];if(x.call(v,y,u,a))return{i:u,v:y}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,x,v){if(v.get||v.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[x]=v.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,x,v,r){if(x){v=$jscomp.global;a=a.split(".");for(r=0;r<a.length-1;r++){var u=a[r];u in v||(v[u]={});v=v[u]}a=a[a.length-1];r=v[a];x=x(r);x!=r&&null!=x&&$jscomp.defineProperty(v,a,{configurable:!0,writable:!0,value:x})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,v){return $jscomp.findInternal(this,a,v).v}},"es6-impl","es3");
(function(a,x){"function"===typeof define&&define.amd?define(["jquery","./grid.base","./jquery.fmatter","./grid.common"],function(v){return x(v,a,a.document)}):"object"===typeof module&&module.exports?module.exports=function(a,r){a||(a=window);void 0===r&&(r="undefined"!==typeof window?require("jquery"):require("jquery")(a));require("./grid.base");require("./jquery.fmatter");require("./grid.common");x(r);return r}:x(jQuery)})("undefined"!==typeof window?window:this,function(a,x,v){var r=a.jgrid,u=
r.jqID,y=a.fn.jqGrid,G=y.getGuiStyles,Z=y.getGridRes;r.extend({getColProp:function(a){var b=this[0];return null!=b&&b.grid&&(a=b.p.iColByName[a],void 0!==a)?b.p.colModel[a]:{}},setColProp:function(f,b){return this.each(function(){var e=this.p,c;this.grid&&null!=e&&b&&(c=e.iColByName[f],void 0!==c&&a.extend(!0,e.colModel[c],b))})},sortGrid:function(a,b,e){return this.each(function(){var c=this.grid,d=this.p,f=d.colModel,k=f.length,g,p,q=!1;if(c)for(a||(a=d.sortname),"boolean"!==typeof b&&(b=!1),p=
0;p<k;p++)if(g=f[p],g.index===a||g.name===a){!0===d.frozenColumns&&!0===g.frozen&&(q=c.fhDiv.find("#"+d.id+"_"+a));q&&0!==q.length||(q=c.headers[p].el);c=g.sortable;("boolean"!==typeof c||c)&&this.sortData("jqgh_"+d.id+"_"+a,p,b,e,q);break}})},clearBeforeUnload:function(){return this.each(function(){var f=this.p,b=this.grid,e,c=r.clearArray,d=Object.prototype.hasOwnProperty;a.isFunction(b.emptyRows)&&b.emptyRows.call(this,!0,!0);a(v).off("mousemove.jqGrid mouseup.jqGrid"+f.id);a(this).off();var l,
k=b.headers.length;for(l=0;l<k;l++)b.headers[l].el=null;for(e in b)b.hasOwnProperty(e)&&(b.propOrMethod=null);b="formatCol sortData updatepager refreshIndex setHeadCheckBox constructTr clearToolbar fixScrollOffsetAndhBoxPadding rebuildRowIndexes modalAlert toggleToolbar triggerToolbar formatter addXmlData addJSONData ftoolbar _inlinenav nav grid p".split(" ");k=b.length;for(l=0;l<k;l++)d.call(this,b[l])&&(this[b[l]]=null);this._index={};c(f.data);c(f.lastSelectedData);c(f.selarrrow);c(f.savedRow)})},
GridDestroy:function(){return this.each(function(){var f=this.p;if(this.grid&&null!=f){f.pager&&a(f.pager).remove();try{a("#alertmod_"+u(f.id)).remove(),a(this).jqGrid("clearBeforeUnload"),a(f.gBox).remove()}catch(b){}}})},GridUnload:function(){return this.each(function(){var f=a(this),b=this.p,e=a.fn.jqGrid;this.grid&&(f.removeClass(e.getGuiStyles.call(f,"grid","ui-jqgrid-btable")),b.pager&&a(b.pager).empty().removeClass(e.getGuiStyles.call(f,"pagerBottom","ui-jqgrid-pager")).removeAttr("style").removeAttr("dir"),
f.jqGrid("clearBeforeUnload"),f.removeAttr("style").removeAttr("tabindex").removeAttr("role").removeAttr("aria-labelledby").removeAttr("style"),f.empty(),f.insertBefore(b.gBox).show(),a(b.pager).insertBefore(b.gBox).show(),a(b.gBox).remove())})},setGridState:function(f){return this.each(function(){var b=this.p,e=this.grid,c=e.cDiv,d=a(e.uDiv),l=a(e.ubDiv);if(e&&null!=b){var e=y.getIconRes.call(this,"gridMinimize.visible"),k=y.getIconRes.call(this,"gridMinimize.hidden");"hidden"===f?(a(".ui-jqgrid-bdiv, .ui-jqgrid-hdiv",
b.gView).slideUp("fast"),b.pager&&a(b.pager).slideUp("fast"),b.toppager&&a(b.toppager).slideUp("fast"),!0===b.toolbar[0]&&("both"===b.toolbar[1]&&l.slideUp("fast"),d.slideUp("fast")),b.footerrow&&a(".ui-jqgrid-sdiv",b.gBox).slideUp("fast"),a(".ui-jqgrid-titlebar-close span",c).removeClass(e).addClass(k),b.gridstate="hidden"):"visible"===f&&(a(".ui-jqgrid-hdiv, .ui-jqgrid-bdiv",b.gView).slideDown("fast"),b.pager&&a(b.pager).slideDown("fast"),b.toppager&&a(b.toppager).slideDown("fast"),!0===b.toolbar[0]&&
("both"===b.toolbar[1]&&l.slideDown("fast"),d.slideDown("fast")),b.footerrow&&a(".ui-jqgrid-sdiv",b.gBox).slideDown("fast"),a(".ui-jqgrid-titlebar-close span",c).removeClass(k).addClass(e),b.gridstate="visible")}})},filterToolbar:function(f){return this.each(function(){var b=this,e=b.grid,c=a(b),d=b.p,l=r.info_dialog,k=r.htmlEncode;if(!this.ftoolbar){var g=a.extend(!0,{autosearch:!0,autosearchDelay:500,searchOnEnter:!0,beforeSearch:null,afterSearch:null,beforeClear:null,afterClear:null,searchurl:"",
stringResult:!1,groupOp:"AND",defaultSearch:"bw",idMode:"new",searchOperators:!1,resetIcon:"&times;",applyLabelClasses:!0,loadFilterDefaults:!0,operands:{eq:"==",ne:"!",lt:"<",le:"<=",gt:">",ge:">=",bw:"^",bn:"!^","in":"=",ni:"!=",ew:"|",en:"!@",cn:"~",nc:"!~",nu:"#",nn:"!#"}},r.search,d.searching||{},f||{}),p=d.colModel,q=function(a){return Z.call(c,a)},S=q("errors.errcap"),x=q("edit.bClose"),Y=q("edit.msg"),O=G.call(b,"states.hover"),z=G.call(b,"states.select"),H=G.call(b,"filterToolbar.dataField"),
I={},C=function(a){var b="gs_";switch(g.idMode){case "compatibility":b+=d.idPrefix;break;case "new":b+=d.id+"_"}return b+a},B=function(a){a=(a.value||"").split(":");return{on:a[0]||"on",off:a[1]||"off"}},y=function(b){var h;h=d.postData.filters;var c={},t,e,n,f;if(b)for(b=0;b<p.length;b++)n=p[b],!1!==n.search&&(f=n.searchoptions||{},c[n.name]={op:f.sopt?f.sopt[0]:"select"===n.stype||"checkbox"===n.stype?"eq":g.defaultSearch,data:void 0!==f.defaultValue?f.defaultValue:""});if(!h||!d.search)return c;
if("string"===typeof h)try{h=a.parseJSON(h)}catch(ba){h={}}else h=h||{};t=h.rules||{};if(null==h||null!=h.groupOp&&null!=g.groupOp&&h.groupOp.toUpperCase()!==g.groupOp.toUpperCase()||null==t||0===t.length||null!=h.groups&&0<h.groups.length)return c;for(b=0;b<t.length;b++)for(e=t[b],h=0;h<p.length;h++)if(n=p[h],(n.index||n.name)===e.field&&!1!==n.search){f=n.searchoptions||{};if(f.sopt){if(0>a.inArray(e.op,f.sopt))continue}else if("select"===n.stype||"checkbox"===n.stype){if("eq"!==e.op)continue}else if(e.op!==
g.defaultSearch)continue;c[n.name]={op:e.op,data:e.data}}return c},E=function(a,b){switch(b){case 1:a.data("state",1).prop({checked:!0,indeterminate:!1});break;case 0:a.data("state",0).prop({checked:!1,indeterminate:!1});break;default:a.data("state",-1).prop({checked:!1,indeterminate:!0})}},J=function(){var n={},h=0,f={};a.each(p,function(){var c=this,t=c.index||c.name,m,l,A=c.searchoptions||{};m=a("#"+u(C(c.name)),!0===c.frozen&&!0===d.frozenColumns?e.fhDiv:e.hDiv);var D=function(a,b){var d=c.formatoptions||
{};return void 0!==d[a]?d[a]:q("formatter."+(b||c.formatter)+"."+a)},w=function(a){var b=D("thousandsSeparator").replace(/([\.\*\_\'\(\)\{\}\+\?\\])/g,"\\$1");return a.replace(new RegExp(b,"g"),"")};l=g.searchOperators?m.parent().prev().children("a").data("soper")||g.defaultSearch:A.sopt?A.sopt[0]:"select"===c.stype||"checkbox"===c.stype?"eq":g.defaultSearch;if("custom"===c.stype&&a.isFunction(A.custom_value)&&0<m.length&&"SPAN"===m[0].nodeName.toUpperCase())m=A.custom_value.call(b,m.children(".customelement").first(),
"get");else if("select"===c.stype)m.prop("multiple")?(m=m.val(),m=null==m||0===m.length?"":m.join(d.inFilterSeparator||",")):m=m.val();else if("checkbox"===c.stype)switch(w=B(A),m.data("state")){case -1:m="";break;case 0:m=w.off;break;default:m=w.on}else switch(m=a.trim(m.val()),c.formatter){case "integer":m=w(m).replace(D("decimalSeparator","number"),".");""!==m&&(m=String(parseInt(m,10)));break;case "number":m=w(m).replace(D("decimalSeparator"),".");""!==m&&"0"===String(m).charAt(0)&&(m=String(parseFloat(m)));
break;case "currency":var A=D("prefix"),k=D("suffix");A&&A.length&&(m=m.substr(A.length));k&&k.length&&(m=m.substr(0,m.length-k.length));m=w(m).replace(D("decimalSeparator"),".");""!==m&&(m=String(parseFloat(m)))}if(m||"nu"===l||"nn"===l||0<=a.inArray(l,d.customUnaryOperations))n[t]=m,f[t]=l,h++;else if(n.hasOwnProperty(t)&&delete n[t],!g.stringResult&&!g.searchOperators&&"local"!==d.datatype)try{null!=d.postData&&d.postData.hasOwnProperty(t)&&delete d.postData[t]}catch(M){}});var A=0<h?!0:!1;if(g.stringResult||
g.searchOperators||"local"===d.datatype){var l='{"groupOp":"'+g.groupOp+'","rules":[',k=0;a.each(n,function(a,b){0<k&&(l+=",");l+='{"field":"'+a+'",';l+='"op":"'+f[a]+'",';l+='"data":"'+(b+"").replace(/\\/g,"\\\\").replace(/\"/g,'\\"')+'"}';k++});l+="]}";a.extend(d.postData,{filters:l});a.each(["searchField","searchString","searchOper"],function(a,b){d.postData.hasOwnProperty(b)&&delete d.postData[b]})}else a.extend(d.postData,n);var U;d.searchurl&&(U=d.url,c.jqGrid("setGridParam",{url:d.searchurl}));
var w="stop"===c.triggerHandler("jqGridToolbarBeforeSearch")?!0:!1;!w&&a.isFunction(g.beforeSearch)&&(w=g.beforeSearch.call(b));w||c.jqGrid("setGridParam",{search:A}).trigger("reloadGrid",[a.extend({page:1},g.reloadGridSearchOptions||{})]);U&&c.jqGrid("setGridParam",{url:U});c.triggerHandler("jqGridToolbarAfterSearch");a.isFunction(g.afterSearch)&&g.afterSearch.call(b)},L=q("search.odata")||[],n=d.customSortOperations,w=function(f,h,e){a("#sopt_menu").remove();h=parseInt(h,10);e=parseInt(e,10)+18;
var A,t=0,l=[],w=a(f).data("soper"),t=a(f).data("colname"),D=a(".ui-jqgrid-view").css("font-size")||"11px";h="<ul id='sopt_menu' class='"+G.call(b,"searchToolbar.menu","ui-search-menu")+"' role='menu' tabindex='0' style='z-index:9999;display:block;font-size:"+D+";left:"+h+"px;top:"+e+"px;'>";t=d.iColByName[t];if(void 0!==t){t=p[t];e=a.extend({},t.searchoptions);var q,r;e.sopt||(e.sopt=[],e.sopt[0]="select"===t.stype||"checkbox"===t.stype?"eq":g.defaultSearch);a.each(L,function(){l.push(this.oper)});
null!=n&&a.each(n,function(a){l.push(a)});for(t=0;t<e.sopt.length;t++)D=e.sopt[t],A=a.inArray(D,l),-1!==A&&(A=L[A],void 0!==A?(r=g.operands[D],q=A.text):null!=n&&(q=n[D],r=q.operand,q=q.text),A=w===D?z:"",h+='<li class="ui-menu-item '+A+'" role="presentation"><a class="ui-corner-all g-menu-item" tabindex="0" role="menuitem" value="'+k(D)+'" data-oper="'+k(r)+'"><table><tr><td style="width:25px">'+k(r)+"</td><td>"+k(q)+"</td></tr></table></a></li>");h+="</ul>";a("body").append(h);a("#sopt_menu").addClass("ui-menu ui-widget ui-widget-content ui-corner-all");
a("#sopt_menu > li > a").hover(function(){a(this).addClass(O)},function(){a(this).removeClass(O)}).click(function(){var b=a(this).attr("value"),h=a(this).data("oper");c.triggerHandler("jqGridToolbarSelectOper",[b,h,f]);a("#sopt_menu").hide();a(f).data("soper",b).text(h);!0===g.autosearch&&(h=a(f).parent().next().children()[0],(a(h).val()||"nu"===b||"nn"===b||0<=a.inArray(b,d.customUnaryOperations))&&J())})}},X,P=[],Q=a("<tr></tr>",{"class":"ui-search-toolbar",role:"row form"});g.loadFilterDefaults&&
(I=y()||{});a.each(p,function(c){var h,e,f,t,w,k=this.searchoptions||{},p=this.editoptions||{},u=a("<th></th>",{"class":G.call(b,"colHeaders","ui-th-column ui-th-"+d.direction+" "+(g.applyLabelClasses?this.labelClasses||"":"")),role:"gridcell","aria-describedby":d.id+"_"+this.name}),V=a("<div></div>"),m;e=a("<table class='ui-search-table'><tbody><tr><td class='ui-search-oper'></td><td class='ui-search-input'></td><td class='ui-search-clear' style='width:1px'></td></tr></tbody></table>");var z=e.children("tbody").children("tr").children("td"),
B=z.eq(0),y=z.eq(1),z=z.eq(2);!0===this.hidden&&u.css("display","none");this.search=!1===this.search?!1:!0;void 0===this.stype&&(this.stype="text");h=a.extend({mode:"filter"},k);if(this.search){if(g.searchOperators){t=d.search&&null!=I[this.name]?I[this.name].op:h.sopt?h.sopt[0]:"select"===this.stype||"checkbox"===this.stype?"eq":g.defaultSearch;for(w=0;w<L.length;w++)if(L[w].oper===t){f=g.operands[t]||"";break}if(void 0===f&&null!=n)for(var T in n)if(n.hasOwnProperty(T)&&T===t){f=n[T].operand;break}void 0===
f&&(f="=");B.append("<a title='"+(null!=h.searchtitle?h.searchtitle:q("search.operandTitle"))+"' data-soper='"+t+"' class='"+G.call(b,"searchToolbar.operButton","soptclass")+"' data-colname='"+this.name+"'>"+f+"</a>")}B.data("colindex",c);null!=h.sopt&&1!==h.sopt.length||B.hide();d.search&&null!=I[this.name]&&(h.defaultValue=I[this.name].data);void 0===h.clearSearch&&(h.clearSearch="text"===this.stype?!0:!1);h.clearSearch?(f=a.isFunction(g.resetTitle)?g.resetTitle.call(b,{options:g,cm:this,cmName:this.name,
iCol:c}):(q("search.resetTitle")||"Clear Search Value")+" "+r.stripHtml(d.colNames[c]),z.append("<a title='"+f+"' aria-label='"+f+"' class='"+G.call(b,"searchToolbar.clearButton","clearsearchclass")+"'><span>"+g.resetIcon+"</span></a>")):z.hide();V.append(e);switch(this.stype){case "checkbox":c=void 0!==h.defaultValue?h.defaultValue:"-1";k=a("<input role='search' type='checkbox' class='"+H+"' name='"+(this.index||this.name)+"' id='"+C(this.name)+"' aria-labelledby='jqgh_"+d.id+"_"+this.name+"' data-state='"+
c+"'/>");"-1"===c?k.prop("indeterminate",!0):"1"===c&&k.prop("checked",!0);k.click(function(){var b=a(this);switch(b.data("state")){case -1:E(b,1);break;case 0:E(b,-1);break;default:E(b,0)}!0===g.autosearch&&J()});y.append(k);h.attr&&k.attr(h.attr);P.push({elem:k[0],options:h});break;case "select":if(e=this.surl||h.dataUrl)a.ajax(a.extend({url:e,context:{$tdInput:y,options:h,cm:this,iCol:c},dataType:"html",success:function(d,c,e){c=this.cm;var f=this.iCol,n=this.options,m=this.$tdInput;void 0!==n.buildSelect?
(d=n.buildSelect.call(b,d,e,c,f))&&m.append(d):m.append(d);e=m.children("select");e.attr({name:c.index||c.name,id:C(c.name)});n.attr&&e.attr(n.attr);e.addClass(H);e.css({width:"100%"});0===e.find("option[value='']").length&&"string"===typeof h.noFilterText&&(d=v.createElement("option"),d.value="",d.innerHTML=h.noFilterText,e.prepend(d),null!=a(e[0].options[e[0].selectedIndex]).attr("selected")||e[0].multiple||(e[0].selectedIndex=0));e[0].multiple&&0===e.find("option[selected]").length&&-1!==e[0].selectedIndex&&
(e[0].options[e[0].selectedIndex].selected=!1);void 0!==n.defaultValue&&e.val(n.defaultValue);r.bindEv.call(b,e[0],n);r.fullBoolFeedback.call(b,n.selectFilled,"jqGridSelectFilled",{elem:e[0],options:n,cm:c,cmName:c.name,iCol:f,mode:"filter"});!0===g.autosearch&&e.change(function(){J();return!1})}},r.ajaxOptions,d.ajaxSelectOptions||{}));else{var F,M,K;this.searchoptions?(F=void 0===k.value?p.value||"":k.value,M=void 0===k.separator?p.separator||":":k.separator,K=void 0===k.delimiter?p.delimiter||
";":k.delimiter):this.editoptions&&(F=void 0===p.value?"":p.value,M=void 0===p.separator?":":p.separator,K=void 0===p.delimiter?";":p.delimiter);e=d.indexByColumnData[this.name];if(k.generateValue&&null!=e){var W;F="";for(m in e)if(e.hasOwnProperty(m)){for(W in e[m])if(e[m].hasOwnProperty(W)){m=e[m][W];break}""!==F&&(F+=K||";");F+=m+M+m}}F&&(m=v.createElement("select"),m.style.width="100%",k=a(m).attr({name:this.index||this.name,role:"search",id:C(this.name),"aria-describedby":d.id+"_"+this.name}),
h.attr&&k.attr(h.attr),r.fillSelectOptions(m,F,M,K,null!=h.attr&&h.attr.multiple)||"string"!==typeof h.noFilterText||(F=v.createElement("option"),F.value="",F.innerHTML=h.noFilterText,F.selected=!0,k.prepend(F)),void 0!==h.defaultValue&&k.val(h.defaultValue),k.addClass(H),P.push({elem:m,options:h}),y.append(m),r.fullBoolFeedback.call(b,h.selectFilled,"jqGridSelectFilled",{elem:m,options:this.searchoptions||p,cm:this,cmName:this.name,iCol:c,mode:"filter"}),!0===g.autosearch&&k.change(function(){J();
return!1}))}break;case "text":k=a("<input role='search' type='text' class='"+H+"' name='"+(this.index||this.name)+"' id='"+C(this.name)+"' aria-labelledby='jqgh_"+d.id+"_"+this.name+"' value='"+(void 0!==h.defaultValue?h.defaultValue:"")+"'/>");y.append(k);h.attr&&k.attr(h.attr);P.push({elem:k[0],options:h});!0===g.autosearch&&(g.searchOnEnter?k.keypress(function(a){return 13===(a.charCode||a.keyCode||0)?(J(),!1):this}):k.keydown(function(a){switch(a.which){case 13:return!1;case 9:case 16:case 37:case 38:case 39:case 40:case 27:break;
default:X&&clearTimeout(X),X=setTimeout(function(){J()},g.autosearchDelay)}}));break;case "custom":y.append("<span style='width:100%;padding:0;box-sizing:border-box;' class='"+H+"' name='"+(this.index||this.name)+"' id='"+C(this.name)+"'/>");try{if(a.isFunction(h.custom_element)){var R=h.custom_element.call(b,void 0!==h.defaultValue?h.defaultValue:"",h);if(R)R=a(R).addClass("customelement"),V.find("span[name='"+(this.index||this.name)+"']").append(R);else throw"e2";}else throw"e1";}catch(N){"e1"===
N&&l.call(b,S,"function 'custom_element' "+Y.nodefined,x),"e2"===N?l.call(b,S,"function 'custom_element' "+Y.novalue,x):l.call(b,S,"string"===typeof N?N:N.message,x)}}}u.append(V);u.find(".ui-search-oper .soptclass,.ui-search-clear .clearsearchclass").hover(function(){a(this).addClass(O)},function(){a(this).removeClass(O)});Q.append(u);g.searchOperators||B.hide()});a(e.hDiv).find(">div>.ui-jqgrid-htable>thead").append(Q);a.each(P,function(){r.bindEv.call(b,this.elem,this.options)});g.searchOperators&&
(a(".soptclass",Q).click(function(b){var d=a(this).offset();w(this,d.left,d.top);b.stopPropagation()}),a("body").on("click",function(b){"soptclass"!==b.target.className&&a("#sopt_menu").hide()}));a(".clearsearchclass",Q).click(function(){var b=a(this).closest(".ui-search-clear"),c=b.siblings(".ui-search-oper"),e=c.children("a"),f=e.data("soper"),c=parseInt(c.data("colindex"),10),b=b.siblings(".ui-search-input"),c=p[c],k=a.extend({},c.searchoptions||{}),l=k.defaultValue||"";switch(c.stype){case "select":l?
b.find("select").val(l):b.find("select")[0].selectedIndex=0;break;case "checkbox":E(b.find("input[type=checkbox]"),-1);break;default:b.find("input").val(l)}if("nu"===f||"nn"===f||0<=a.inArray(f,d.customUnaryOperations))f=k.sopt?k.sopt[0]:"select"===c.stype||"checkbox"===c.stype?"eq":g.defaultSearch,b=null!=n&&null!=n[f]?n[f].operand:g.operands[f]||"",e.data("soper",f).text(b);!0===g.autosearch&&J()});b.ftoolbar=!0;b.triggerToolbar=J;b.clearToolbar=function(f){var h={},n=0,k;f="boolean"!==typeof f?
!0:f;a.each(p,function(){var c,f=a("#"+u(C(this.name)),!0===this.frozen&&!0===d.frozenColumns?e.fhDiv:e.hDiv),g,l=this.searchoptions||{};void 0!==l.defaultValue&&(c=l.defaultValue);k=this.index||this.name;switch(this.stype){case "checkbox":E(f,-1);break;case "select":g=0<f.length?!f[0].multiple:!0;f.find("option").each(function(b){this.selected=0===b&&g;if(a(this).val()===c)return this.selected=!0,!1});if(void 0!==c)h[k]=c,n++;else try{delete d.postData[k]}catch(aa){}break;case "text":f.val(c||"");
if(void 0!==c)h[k]=c,n++;else try{delete d.postData[k]}catch(aa){}break;case "custom":a.isFunction(l.custom_value)&&0<f.length&&"SPAN"===f[0].nodeName.toUpperCase()&&l.custom_value.call(b,f.children(".customelement").first(),"set",c||"")}});var l=0<n?!0:!1;d.resetsearch=!0;if(g.stringResult||g.searchOperators||"local"===d.datatype){var w='{"groupOp":"'+g.groupOp+'","rules":[',t=0;a.each(h,function(a,b){0<t&&(w+=",");w+='{"field":"'+a+'",';w+='"op":"eq",';w+='"data":"'+(b+"").replace(/\\/g,"\\\\").replace(/\"/g,
'\\"')+'"}';t++});w+="]}";a.extend(d.postData,{filters:w});a.each(["searchField","searchString","searchOper"],function(a,b){d.postData.hasOwnProperty(b)&&delete d.postData[b]})}else a.extend(d.postData,h);var q;d.searchurl&&(q=d.url,c.jqGrid("setGridParam",{url:d.searchurl}));var r="stop"===c.triggerHandler("jqGridToolbarBeforeClear")?!0:!1;!r&&a.isFunction(g.beforeClear)&&(r=g.beforeClear.call(b));r||f&&c.jqGrid("setGridParam",{search:l}).trigger("reloadGrid",[a.extend({page:1},g.reloadGridResetOptions||
{})]);q&&c.jqGrid("setGridParam",{url:q});c.triggerHandler("jqGridToolbarAfterClear");a.isFunction(g.afterClear)&&g.afterClear.call(b)};b.toggleToolbar=function(){var b=a("tr.ui-search-toolbar",e.hDiv),f=!0===d.frozenColumns?a("tr.ui-search-toolbar",e.fhDiv):!1;"none"===b.css("display")?(b.show(),f&&f.show()):(b.hide(),f&&f.hide());!0===d.frozenColumns&&(c.jqGrid("destroyFrozenColumns"),c.jqGrid("setFrozenColumns"))};!0===d.frozenColumns&&(c.jqGrid("destroyFrozenColumns"),c.jqGrid("setFrozenColumns"));
c.on("jqGridRefreshFilterValues.filterToolbar"+(g.loadFilterDefaults?" jqGridAfterLoadComplete.filterToolbar":""),function(){var b,c,f=y(!0)||{},e;if(g.stringResult||g.searchOperators||"local"===d.datatype||!d.search){for(b in f)if(f.hasOwnProperty(b)&&(c=f[b],e=a("#"+u(C(b))),0<e.length)){if("SELECT"===e[0].tagName.toUpperCase()&&e[0].multiple)e.val(c.data.split(d.inFilterSeparator||","));else if(e.is("input[type=checkbox]")){var n=e.closest("th.ui-th-column");0<n.length&&(n=B((d.colModel[n[0].cellIndex]||
{}).searchoptions||{}),E(e,c.data===n.on?1:c.data===n.off?0:-1))}else a.trim(e.val())!==c.data&&e.val(c.data);e=e.closest(".ui-search-input").siblings(".ui-search-oper").children(".soptclass");e.data("soper",c.op);e.text(g.operands[c.op])}for(c=0;c<d.colModel.length;c++)b=d.colModel[c].name,f.hasOwnProperty(b)||a("#"+u(C(b))).val("")}})}})},destroyFilterToolbar:function(){return this.each(function(){this.ftoolbar&&(this.toggleToolbar=this.clearToolbar=this.triggerToolbar=null,this.ftoolbar=!1,a(this.grid.hDiv).find("table thead tr.ui-search-toolbar").remove(),
!0===this.p.frozenColumns&&a(this).jqGrid("destroyFrozenColumns").jqGrid("setFrozenColumns"))})},destroyGroupHeader:function(f){void 0===f&&(f=!0);return this.each(function(){var b,e,c,d;b=this.grid;var l=this.p.colModel,k=a("table.ui-jqgrid-htable thead",b.hDiv);if(b){a(this).off(".setGroupHeaders");var g=a("<tr>",{role:"row"}).addClass("ui-jqgrid-labels"),p=b.headers;b=0;for(e=p.length;b<e;b++){c=l[b].hidden?"none":"";c=a(p[b].el).width(p[b].width).css("display",c);try{c.removeAttr("rowSpan")}catch(q){c.attr("rowSpan",
1)}g.append(c);d=c.children("span.ui-jqgrid-resize");0<d.length&&(d[0].style.height="");c.children("div")[0].style.top=""}a(k).children("tr.ui-jqgrid-labels").remove();a(k).prepend(g);!0===f&&a(this).jqGrid("setGridParam",{groupHeader:null})}})},setGroupHeaders:function(f){f=a.extend({useColSpanStyle:!1,applyLabelClasses:!0,groupHeaders:[]},f||{});return this.each(function(){this.p.groupHeader=f;var b,e,c=0,d,l,k,g,p,q,u=this.p,v=u.colModel,x=v.length,y=this.grid.headers,z=a("table.ui-jqgrid-htable",
this.grid.hDiv),H=r.isCellClassHidden,I=z.children("thead").children("tr.ui-jqgrid-labels"),C=I.last().addClass("jqg-second-row-header");d=z.children("thead");var B=z.find(".jqg-first-row-header");void 0===B[0]?B=a("<tr>",{role:"row","aria-hidden":"true"}).addClass("jqg-first-row-header").css("height","auto"):B.empty();var K=function(a,b){var c;for(c=0;c<b.length;c++)if(b[c].startColumnName===a)return b[c];return 0};a(this).prepend(d);d=a("<tr>",{role:"row"}).addClass("ui-jqgrid-labels jqg-third-row-header");
for(b=0;b<x;b++)if(k=y[b].el,g=a(k),e=v[b],l={height:"0",width:y[b].width+"px",display:e.hidden?"none":""},a("<th>",{role:"gridcell"}).css(l).addClass("ui-first-th-"+u.direction+(f.applyLabelClasses?" "+(e.labelClasses||""):"")).appendTo(B),k.style.width="",l=G.call(this,"colHeaders","ui-th-column-header ui-th-"+u.direction+" "+(f.applyLabelClasses?e.labelClasses||"":"")),p=K(e.name,f.groupHeaders)){c=p.numberOfColumns;q=p.titleText;for(p=e=0;p<c&&b+p<x;p++)v[b+p].hidden||H(v[b+p].classes)||e++;l=
a("<th>").addClass(l).css({height:"22px","border-top":"0 none"}).html(q);0<e&&l.attr("colspan",String(e));u.headertitles&&l.attr("title",l.text());0===e&&l.hide();g.before(l);d.append(k);--c}else 0===c?f.useColSpanStyle?g.attr("rowspan",I.length+1):(a("<th>").addClass(l).css({display:e.hidden?"none":"","border-top":"0 none"}).insertBefore(g),d.append(k)):(d.append(k),c--);u=a(this).children("thead");u.prepend(B);d.insertAfter(C);z.prepend(u);f.useColSpanStyle&&(z.find("span.ui-jqgrid-resize").each(function(){var b=
a(this).parent();b.is(":visible")&&(this.style.cssText="height:"+b.height()+"px !important;cursor:col-resize;")}),z.find(".ui-th-column>div").each(function(){var b=a(this),c=b.parent();c.is(":visible")&&c.is(":has(span.ui-jqgrid-resize)")&&!b.hasClass("ui-jqgrid-rotate")&&!b.hasClass("ui-jqgrid-rotateOldIE")&&b.css("top",(c.height()-b.outerHeight(!0))/2+"px")}));a(this).triggerHandler("jqGridAfterSetGroupHeaders")})},getNumberOfFrozenColumns:function(){var a=this;if(0===a.length)return 0;var a=a[0],
a=a.p.colModel,b=a.length,e=-1,c;for(c=0;c<b&&!0===a[c].frozen;c++)e=c;return e+1},setFrozenColumns:function(f){f=f||{};return this.each(function(){var b=this,e=a(b),c=b.p,d=b.grid;if(d&&null!=c&&!0!==c.frozenColumns){var l=c.colModel,k,g=l.length,p=-1,q=!1,r=[],v=u(c.id),x=G.call(b,"states.hover"),y=G.call(b,"states.disabled");if(!0!==c.subGrid&&!0!==c.treeGrid&&!c.scroll){for(k=0;k<g&&!0===l[k].frozen;k++)q=!0,p=k,r.push("#jqgh_"+v+"_"+u(l[k].name));c.sortable&&(l=a(d.hDiv).find(".ui-jqgrid-htable .ui-jqgrid-labels"),
l.sortable("destroy"),e.jqGrid("setGridParam",{sortable:{options:{items:0<r.length?">th:not(:has("+r.join(",")+"),:hidden)":">th:not(:hidden)"}}}),e.jqGrid("sortableColumns",l));if(0<=p&&q){q=c.caption?a(d.cDiv).outerHeight():0;r=a(".ui-jqgrid-htable",c.gView).height();c.toppager&&(q+=a(d.topDiv).outerHeight());!0===c.toolbar[0]&&"bottom"!==c.toolbar[1]&&(q+=a(d.uDiv).outerHeight());d.fhDiv=a("<div style='position:absolute;overflow:hidden;"+("rtl"===c.direction?"right:0;border-top-left-radius:0;":
"left:0;border-top-right-radius:0;")+"top:"+q+"px;height:"+r+"px;' class='"+G.call(b,"hDiv","frozen-div ui-jqgrid-hdiv")+"'></div>");d.fbDiv=a("<div style='position:absolute;overflow:hidden;"+("rtl"===c.direction?"right:0;":"left:0;")+"top:"+(parseInt(q,10)+parseInt(r,10)+1)+"px;overflow:hidden;' class='frozen-bdiv ui-jqgrid-bdiv'></div>");a(c.gView).append(d.fhDiv);l=a(".ui-jqgrid-htable",c.gView).clone(!0);g=l[0].tHead.rows;if(c.groupHeader){a(g[0].cells).filter(":gt("+p+")").remove();a(g).filter(".jqg-third-row-header").each(function(){a(this).children("th[id]").each(function(){var d=
a(this).attr("id");d&&d.substr(0,b.id.length+1)===b.id+"_"&&(d=d.substr(b.id.length+1),c.iColByName[d]>p&&a(this).remove())})});var z=-1,H=-1,I,C;a(g).filter(".jqg-second-row-header").children("th").each(function(){I=parseInt(a(this).attr("colspan")||1,10);C=parseInt(a(this).attr("rowspan")||1,10);1<C?(z++,H++):I&&(z+=I,H++);if(z===p)return!1});z!==p&&(H=p);a(g).filter(".jqg-second-row-header,.ui-search-toolbar").each(function(){a(this).children(":gt("+H+")").remove()})}else a(g).each(function(){a(this).children(":gt("+
p+")").remove()});a(l).width(1);a(d.fhDiv).append(l).scroll(function(){this.scrollLeft=0});c.footerrow&&(l=a(".ui-jqgrid-bdiv",c.gView).height(),d.fsDiv=a("<div style='position:absolute;"+("rtl"===c.direction?"right:0;":"left:0;")+"top:"+(parseInt(q,10)+parseInt(r,10)+parseInt(l,10)+1)+"px;' class='frozen-sdiv ui-jqgrid-sdiv'></div>"),a(c.gView).append(d.fsDiv),q=a(".ui-jqgrid-ftable",c.gView).clone(!0),a("tr",q).each(function(){a("td:gt("+p+")",this).remove()}),a(q).width(1),a(d.fsDiv).append(q));
e.on("jqGridSortCol.setFrozenColumns",function(b,e,f){b=a("tr.ui-jqgrid-labels:last th:eq("+c.lastsort+")",d.fhDiv);e=a("tr.ui-jqgrid-labels:last th:eq("+f+")",d.fhDiv);a("span.ui-grid-ico-sort",b).addClass(y);a(b).attr("aria-selected","false");a("span.ui-icon-"+c.sortorder,e).removeClass(y);a(e).attr("aria-selected","true");c.viewsortcols[0]||c.lastsort===f||(a("span.s-ico",b).hide(),a("span.s-ico",e).show())});a(c.gView).append(d.fbDiv);a(d.bDiv).scroll(function(){a(d.fbDiv).scrollTop(a(this).scrollTop())});
a(d.fbDiv).on("mousewheel.setFrozenColumns DOMMouseScroll.setFrozenColumns",function(c){d.bDiv.scrollTop+=a.isFunction(f.mouseWheel)?f.mouseWheel.call(b,c):"mousewheel"===c.type?-c.originalEvent.wheelDelta/10:6*c.originalEvent.detail});!0===c.hoverrows&&a(c.idSel).off("mouseover.jqGrid mouseout.jqGrid");var B=function(a,b){var c=a.height();1<=Math.abs(c-b)&&0<b&&(a.height(b),c=a.height(),1<=Math.abs(b-c)&&a.height(b+Math.round(b-c)))},K=function(a,b){var c=a.width();1<=Math.abs(c-b)&&(a.width(b),
c=a.width(),1<=Math.abs(b-c)&&a.width(b+Math.round(b-c)))},E=function(b,d,e,f){var g,l,h,n,p,r,q;q=a(d).position().top;var w,u,v;if(null!=b&&0<b.length){b[0].scrollTop=d.scrollTop;b.css("rtl"===c.direction?{top:q,right:0}:{top:q,left:0});l=b.children("table").children("thead").children("tr");h=a(d).children("div").children("table").children("thead").children("tr");0===h.length&&(l=a(b.children("table")[0].rows),h=a(a(d).children("div").children("table")[0].rows));g=Math.min(l.length,h.length);w=0<
g?a(l[0]).position().top:0;u=0<g?a(h[0]).position().top:0;if(0<=e)for(0<=f&&(g=Math.min(f+1,g));e<g;e++)if(n=a(h[e]),"none"!==n.css("display")&&n.is(":visible")){q=n.position().top;f=a(l[e]);p=f.position().top;r=n.height();if(null!=c.groupHeader&&c.groupHeader.useColSpanStyle)for(v=n[0].cells,k=0;k<v.length;k++)n=v[k],null!=n&&"TH"===n.nodeName.toUpperCase()&&(r=Math.max(r,a(n).height()));q=r+(q-u)+(w-p);B(f,q)}B(b,d.clientHeight)}},q={resizeDiv:!0,resizedRows:{iRowStart:0,iRowEnd:-1}},J={header:q,
resizeFooter:!0,body:q};e.on("jqGridAfterGridComplete.setFrozenColumns",function(){a(c.idSel+"_frozen").remove();a(d.fbDiv).height(d.hDiv.clientHeight);var b=a(this).clone(!0),f=b[0].rows,g=e[0].rows;a(f).filter("tr[role=row]").each(function(){a(this.cells).filter("td[role=gridcell]:gt("+p+")").remove()});d.fbRows=f;b.width(1).attr("id",c.id+"_frozen");b.appendTo(d.fbDiv);if(!0===c.hoverrows){var k=function(b,c,d){a(b)[c](x);a(d[b.rowIndex])[c](x)};a(f).filter(".jqgrow").hover(function(){k(this,"addClass",
g)},function(){k(this,"removeClass",g)});a(g).filter(".jqgrow").hover(function(){k(this,"addClass",f)},function(){k(this,"removeClass",f)})}E(d.fhDiv,d.hDiv,0,-1);E(d.fbDiv,d.bDiv,0,-1);d.sDiv&&E(d.fsDiv,d.sDiv,0,-1)});var L=function(b){a(d.fbDiv).scrollTop(a(d.bDiv).scrollTop());b.header.resizeDiv&&E(d.fhDiv,d.hDiv,b.header.resizedRows.iRowStart,b.header.resizedRows.iRowEnd);b.body.resizeDiv&&E(d.fbDiv,d.bDiv,b.body.resizedRows.iRowStart,b.body.resizedRows.iRowEnd);b.resizeFooter&&d.sDiv&&b.resizeFooter&&
E(d.fsDiv,d.sDiv,0,-1);var c=d.fhDiv[0].clientWidth;b.header.resizeDiv&&null!=d.fhDiv&&1<=d.fhDiv.length&&B(a(d.fhDiv),d.hDiv.clientHeight);b.body.resizeDiv&&null!=d.fbDiv&&0<d.fbDiv.length&&K(a(d.fbDiv),c);b.resizeFooter&&null!=d.fsDiv&&0<=d.fsDiv.length&&K(a(d.fsDiv),c)};a(c.gBox).on("resizestop.setFrozenColumns",function(){setTimeout(function(){L(J)},50)});e.on("jqGridInlineEditRow.setFrozenColumns jqGridInlineAfterRestoreRow.setFrozenColumns jqGridInlineAfterSaveRow.setFrozenColumns jqGridAfterEditCell.setFrozenColumns jqGridAfterRestoreCell.setFrozenColumns jqGridAfterSaveCell.setFrozenColumns jqGridResizeStop.setFrozenColumns",
function(a,b){var c=e.jqGrid("getInd",b);L({header:{resizeDiv:!1,resizedRows:{iRowStart:-1,iRowEnd:-1}},resizeFooter:!0,body:{resizeDiv:!0,resizedRows:{iRowStart:c,iRowEnd:c}}})});e.on("jqGridResizeStop.setFrozenColumns",function(){L(J)});e.on("jqGridResetFrozenHeights.setFrozenColumns",function(a,b){L(b||J)});d.hDiv.loading||e.triggerHandler("jqGridAfterGridComplete");c.frozenColumns=!0}}}})},destroyFrozenColumns:function(){return this.each(function(){var f=a(this),b=this.grid,e=this.p,c=u(e.id);
if(b&&!0===e.frozenColumns){a(b.fhDiv).remove();a(b.fbDiv).off(".setFrozenColumns");a(b.fbDiv).remove();b.fhDiv=null;b.fbDiv=null;b.fbRows=null;e.footerrow&&(a(b.fsDiv).remove(),b.fsDiv=null);f.off(".setFrozenColumns");if(!0===e.hoverrows){var d,l=G.call(this,"states.hover");f.on("mouseover.jqGrid",function(b){d=a(b.target).closest("tr.jqgrow");"ui-subgrid"!==a(d).attr("class")&&a(d).addClass(l)}).on("mouseout.jqGrid",function(b){d=a(b.target).closest("tr.jqgrow");a(d).removeClass(l)})}e.frozenColumns=
!1;e.sortable&&(b=a(b.hDiv).find(".ui-jqgrid-htable .ui-jqgrid-labels"),b.sortable("destroy"),f.jqGrid("setGridParam",{sortable:{options:{items:">th:not(:has(#jqgh_"+c+"_cb,#jqgh_"+c+"_rn,#jqgh_"+c+"_subgrid),:hidden)"}}}),f.jqGrid("sortableColumns",b))}})}})});
//# sourceMappingURL=grid.custom.map
