(function(c){"function"===typeof define&&define.amd?define(["jquery","./grid.base"],c):"object"===typeof exports?c(require("jquery")):c(jQuery)})(function(c){var n=c.jgrid,w=n.jqID,l=c.fn.jqGrid,y=function(){var a=c.makeArray(arguments);a[0]="subGrid"+a[0].charAt(0).toUpperCase()+a[0].substring(1);a.unshift("");a.unshift("");a.unshift(this.p);return n.feedback.apply(this,a)},q=function(a,e){return this.each(function(){if(this.grid&&null!=a&&!0===this.p.subGrid){var d=c(this).jqGrid("getInd",a,!0);
c(d).find(">td."+e).trigger("click")}})};n.extend({setSubGrid:function(){return this.each(function(){var a=this.p,e=a.subGridModel[0];a.subGridOptions=c.extend({expandOnLoad:!1,delayOnLoad:50,selectOnExpand:!1,selectOnCollapse:!1,reloadOnExpand:!0},a.subGridOptions||{});a.colNames.unshift("");a.colModel.unshift({name:"subgrid",width:n.cell_width?a.subGridWidth+a.cellLayout:a.subGridWidth,labelClasses:"jqgh_subgrid",sortable:!1,resizable:!1,hidedlg:!0,search:!1,fixed:!0,frozen:!0});if(e)for(e.align=
c.extend([],e.align||[]),a=0;a<e.name.length;a++)e.align[a]=e.align[a]||"left"})},addSubGridCell:function(a,e,d,b){var k=this[0],f=k.p.subGridOptions;d=c.isFunction(f.hasSubgrid)?f.hasSubgrid.call(k,{rowid:d,iRow:e,iCol:a,data:b}):!0;return null==k||null==k.p||null==f?"":"<td role='gridcell' class='"+l.getGuiStyles.call(this,"subgrid.tdStart",d?"ui-sgcollapsed sgcollapsed":"")+"' "+k.formatCol(a,e)+">"+(d?"<div class='"+l.getGuiStyles.call(this,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+
l.getGuiStyles.call(this,"subgrid.button","sgbutton")+"'><span class='"+n.mergeCssClasses(f.commonIconClass,f.plusicon)+"'></span></a></div>":"&nbsp;")+"</td>"},addSubGrid:function(a,e){return this.each(function(){var d=this,b=d.p,k=b.subGridModel[0],f=function(c,b){return l.getGuiStyles.call(d,"subgrid."+c,b||"")},q=f("thSubgrid","ui-th-subgrid ui-th-column ui-th-"+b.direction),z=f("rowSubTable","ui-subtblcell"),C=f("row","ui-subgrid ui-row-"+b.direction),D=f("tdWithIcon","subgrid-cell"),E=f("tdData",
"subgrid-data"),r=function(b,a,d){a=c("<td align='"+k.align[d]+"'></td>").html(a);b.append(a)},A=function(a,d){var g=b.xmlReader.subgrid;c(g.root+" "+g.row,a).each(function(){var b,a,m=c("<tr class='"+z+"'></tr>");if(!0===g.repeatitems)c(g.cell,this).each(function(b){r(m,c(this).text()||"&#160;",b)});else if(b=k.mapping||k.name)for(a=0;a<b.length;a++)r(m,c(b[a],this).text()||"&#160;",a);d.append(m)})},B=function(a,d){var g,t,h,m,e,f=b.jsonReader.subgrid,l=n.getAccessor(a,f.root);if(null!=l)for(t=
0;t<l.length;t++){e=l[t];g=c("<tr class='"+z+"'></tr>");if(!0===f.repeatitems)for(f.cell&&(e=e[f.cell]),h=0;h<e.length;h++)r(g,e[h]||"&#160;",h);else if(m=k.mapping||k.name,m.length)for(h=0;h<m.length;h++)r(g,e[m[h]]||"&#160;",h);d.append(g)}},u=function(a,e,g){var f,h,m=c("<table"+(n.msie&&8>n.msiever()?" cellspacing='0'":"")+"><tbody></tbody></table>"),l=c(m[0].tBodies[0]),p=c("<tr></tr>");for(h=0;h<k.name.length;h++)f=c("<th class='"+q+"'></th>").html(k.name[h]).width(k.width[h]),p.append(f);l.append(p);
g(a,l);c("#"+w(b.id+"_"+e)).append(m);d.grid.hDiv.loading=!1;c("#load_"+w(b.id)).hide();return!1},F=function(a){var e=c(a).attr("id"),g={nd_:(new Date).getTime()},f,h;g[b.prmNames.subgridid]=e;if(!k)return!1;if(k.params)for(h=0;h<k.params.length;h++)f=b.iColByName[k.params[h]],void 0!==f&&(g[b.colModel[f].name]=c(a.cells[f]).text().replace(/\&#160\;/ig,""));if(!d.grid.hDiv.loading)switch(d.grid.hDiv.loading=!0,c("#load_"+w(b.id)).show(),b.subgridtype||(b.subgridtype=b.datatype),c.isFunction(b.subgridtype)?
b.subgridtype.call(d,g):b.subgridtype=b.subgridtype.toLowerCase(),b.subgridtype){case "xml":case "json":c.ajax(c.extend({type:b.mtype,url:c.isFunction(b.subGridUrl)?b.subGridUrl.call(d,g):b.subGridUrl,dataType:b.subgridtype,data:n.serializeFeedback.call(d,b.serializeSubGridData,"jqGridSerializeSubGridData",g),complete:function(a){"xml"===b.subgridtype?u(a.responseXML,e,A):(a=n.parse(a.responseText),u(a,e,B))}},n.ajaxOptions,b.ajaxSubgridOptions||{}))}return!1},f=function(){var e=c(this).parent("tr")[0],
f=e.nextSibling,g=e.id,k=b.id+"_"+g,h=function(a){return n.mergeCssClasses(b.subGridOptions.commonIconClass,b.subGridOptions[a])},m=1;c.each(b.colModel,function(){!0!==this.hidden&&"rn"!==this.name&&"cb"!==this.name||m++});if(c(this).hasClass("sgcollapsed")){if(!0===b.subGridOptions.reloadOnExpand||!1===b.subGridOptions.reloadOnExpand&&!c(f).hasClass("ui-subgrid")){f=1<=a?"<td colspan='"+a+"'>&#160;</td>":"";if(!y.call(d,"beforeExpand",k,g))return;c(e).after("<tr role='row' class='"+C+"'>"+f+"<td class='"+
D+"'><span class='"+h("openicon")+"'></span></td><td colspan='"+parseInt(b.colNames.length-m,10)+"' class='"+E+"'><div id='"+k+"' class='tablediv'></div></td></tr>");c(d).triggerHandler("jqGridSubGridRowExpanded",[k,g]);c.isFunction(b.subGridRowExpanded)?b.subGridRowExpanded.call(d,k,g):F(e)}else c(f).show();c(this).html("<div class='"+l.getGuiStyles.call(d,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+l.getGuiStyles.call(d,"subgrid.button","sgbutton")+"'><span class='"+h("minusicon")+
"'></span></a></div>").removeClass("sgcollapsed").addClass("sgexpanded");b.subGridOptions.selectOnExpand&&c(d).jqGrid("setSelection",g)}else if(c(this).hasClass("sgexpanded")){if(!y.call(d,"beforeCollapse",k,g))return;!0===b.subGridOptions.reloadOnExpand?c(f).remove(".ui-subgrid"):c(f).hasClass("ui-subgrid")&&c(f).hide();c(this).html("<div class='"+l.getGuiStyles.call(d,"subgrid.buttonDiv","sgbutton-div")+"'><a role='button' class='"+l.getGuiStyles.call(d,"subgrid.button","sgbutton")+"'><span class='"+
h("plusicon")+"'></span></a></div>").removeClass("sgexpanded").addClass("sgcollapsed");b.subGridOptions.selectOnCollapse&&c(d).jqGrid("setSelection",g)}return!1},x,p,v=1;if(d.grid){x=d.rows.length;void 0!==e&&0<e&&(v=e,x=e+1);for(;v<x;)p=d.rows[v],c(p).hasClass("jqgrow")&&(p=c(p.cells[a]),p.hasClass("ui-sgcollapsed")&&(b.scroll&&p.unbind("click"),p.bind("click",f))),v++;!0===b.subGridOptions.expandOnLoad&&c(d.rows).filter(".jqgrow").each(function(a,b){c(b.cells[0]).click()});d.subGridXml=function(a,
b){u(a,b,A)};d.subGridJson=function(a,b){u(a,b,B)}}})},expandSubGridRow:function(a){return q.call(this,a,"sgcollapsed")},collapseSubGridRow:function(a){return q.call(this,a,"sgexpanded")},toggleSubGridRow:function(a){return q.call(this,a,"ui-sgcollapsed")}})});
//# sourceMappingURL=grid.subgrid.map
